org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official

GROUP=ai.synheart
VERSION_NAME=0.0.1
POM_ARTIFACT_ID=synheart-core-edge
POM_NAME=Synheart Core Edge (Kotlin)
POM_DESCRIPTION=Light Synheart Core SDK for Wear OS / Android edge devices.
POM_URL=https://github.com/synheart-ai/synheart-core-kotlin-edge
POM_LICENSE_NAME=Apache-2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
